---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: True

  tasks:
    - name: Retrieve data from assymetric vault with a private key file.
      ipavault:
        ipaadmin_password: SomeADMINpassword
        name: symvault
        username: admin
        private_key_file: private.pem
        retrieve: True
      register: result
    - debug:
       msg: "Data: {{ result.data }}"
    - debug:
       msg: "Decoded Data: {{ result.data | b64decode }}"
